service: dataproc-twitter
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*/
  script: main.app
  login: admin

- url: /.*
  script: main.app
  login: admin

basic_scaling:
  max_instances: 1
